name: Builds
on:
  workflow_dispatch:
    inputs:
      version:
        description: "LLVM version (default to main), for example release/15.x"
        required: true
        default: "main"
        type: string
      stdlib:
        description: "Choose std library implementation"
        required: true
        default: "libstdc++"
        type: choice
        options:
        - libstdc++
        - libc++
      clang:
        description: "Build clang"
        required: true
        type: boolean
        default: true
      lldb:
        description: "Build lldb"
        required: true
        type: boolean
        default: true
      clang-tools-extra:
        description: "Build clang-tools-extra"
        required: true
        type: boolean
        default: true

jobs:
  msys2:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    strategy:
      fail-fast: false
      matrix:
        sys:
          - UCRT64
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.sys}}
          install: >-
            git
            make
            mingw-w64-ucrt-x86_64-gcc
          pacboy: >-
            cmake:p
      - name: Check latest version
        run: |
          LLVM_VERSION="${{inputs.version || 'main'}}"
          echo LLVM_VERSION=$LLVM_VERSION >> $GITHUB_ENV
          if [ -z "$LLVM_VERSION" ]
          then
            echo "LLVM version is not valid"
            exit 1
          fi
      - uses: actions/checkout@v3
      - name: Build
        run: |
          LLVM_VERSION=${{env.LLVM_VERSION}}
          ./build-llvm.sh "${{github.workspace}}/llvm" --full-llvm \
            ${{(inputs.stdlib == 'libc++') && '--enable-libc++' || ''}} \
            ${{inputs.clang && '--enable-clang' || ''}} \
            ${{inputs.lldb && '--enable-lldb' || ''}} \
            ${{inputs.clang-tools-extra && '--enable-clang-tools-extra' || ''}}
          echo ARTIFACT_NAME=$(echo ${{inputs.version || 'main'}} | sed -r 's/\//-/g') >> $GITHUB_ENV
      - name: Upload zip
        uses: actions/upload-artifact@v3
        with:
          name: llvm-mingw-${{env.ARTIFACT_NAME}}-${{inputs.stdlib}}
          path: ${{github.workspace}}/llvm
