name: Builds
on:
  workflow_dispatch:
    inputs:
      version:
        description: "LLVM version (default to main), for example release/15.x"
        required: true
        default: "main"
        type: string
      clang:
        description: "Compile clang"
        required: true
        type: boolean

jobs:
  msys2:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    strategy:
      fail-fast: false
      matrix:
        sys:
          - UCRT64
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.sys}}
          install: >-
            git
            make
            mingw-w64-ucrt-x86_64-gcc
          pacboy: >-
            cmake:p
      - name: Check latest version
        run: |
          LLVM_VERSION="${{inputs.version || 'main'}}"
          echo LLVM_VERSION=$LLVM_VERSION >> $GITHUB_ENV
          if [ -z "$LLVM_VERSION" ]
          then
            echo "LLVM version is not valid"
            exit 1
          fi
      - uses: actions/checkout@v3
      - name: Build
        run: |
          LLVM_VERSION=${{env.LLVM_VERSION}}
          ./build-llvm.sh "${{github.workspace}}/llvm" --full-llvm ${{inputs.clang ? "--enable-clang" : ""}}
          echo ARTIFACT_NAME=$(echo ${{inputs.version || 'main'}} | sed -r 's/\//-/g') >> $GITHUB_ENV
      - name: Upload zip
        uses: actions/upload-artifact@v3
        with:
          name: llvm-mingw-${{env.ARTIFACT_NAME}}
          path: ${{github.workspace}}/llvm
