name: Builds
on:
  workflow_dispatch:
    inputs:
      version:
        description: "LLVM version (default to main)"
        required: true
        default: "main"
        type: string

jobs:
  msys2:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    strategy:
      fail-fast: false
      matrix:
        sys:
          - mingw64
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.sys}}
          install: >-
            git
            make
            diffutils
          pacboy: >-
            toolchain:p
            cmake:p
      - name: Check latest version
        run: |
          echo LLVM_VERSION=$(git ls-remote https://github.com/llvm/llvm-project.git | grep 'refs/heads/${{inputs.version || 'main'}}$' | awk '{print $1}') >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - name: Build
        run: |
          LLVM_VERSION=${{env.LLVM_VERSION}}
          ./build-llvm.sh "${{github.workspace}}/llvm" --disable-clang-tools-extra --disable-lldb --full-llvm $CFGUARD_PARAMS
      - name: Upload zip
        uses: actions/upload-artifact@v3
        with:
          name: llvm-mingw-${{inputs.version || 'main'}}.zip
          path: ${{github.workspace}}/llvm
